name: Build Windows Executable

on:
  push:
    branches:
      - main  # or any other branch you want to trigger on

jobs:
  build:
    runs-on: windows-latest  # We are using a Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out your code to the runner

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the desired version of Python

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Install PyInstaller

      - name: Compile Python script to .exe
        run: pyinstaller --onefile hallo.py  # Change to your script name

      - name: Upload the .exe file as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/hallo.exe  # The path to the .exe file produced by PyInstaller
