name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Compile Python script to .exe
        run: pyinstaller --onefile hallo.py

      - name: List files in dist directory
        run: |
          dir dist\

      - name: Upload the .exe file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/*.exe
